version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wikirushermdp953
      - MYSQL_DATABASE=dbwikirusher
    ports:
      - 42001:3306

    networks:
      - backend
  front:
    build: 
      context: ./wikirusher-client
    restart: unless-stopped
    ports:
      - 42002:8081
    networks:
      - backend
  back:
    build: ./wikirusher-server
    restart: unless-stopped
    ports:
      - 42003:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASS=wikirushermdp953
      - DB_NAME=dbwikirusher
      - DB_PORT=42001
      - FRONT_BASE_URL=http://wikirusher.prototick.fr
    networks:
      - backend
volumes: 
  db:
networks:
  backend:
    driver: bridge
  
